/* 
 * Nasjonalt Register over Luftfartshindre
 *
 * ## Autentisering Finn autoriserings token her: [https://nrl-test.kartverket.no/token/](https://nrl-test.kartverket.no/token/)   Trykk \"Authorize\" og skriv inn `Bearer <token>`  ## Kontakt oss Spørsmål kan sendes til [nrl@kartverket.no](mailto:nrl@kartverket.no) ## Annen dokumentasjon [Introduksjon til NRL](https://www.kartverket.no/geodataarbeid/nrl)   [SOSI-standardisert produktspesifikasjon - NRL rapportering](https://sosi.geonorge.no/produktspesifikasjoner/NRL-rapportering/)   [NRL - webklient](https://nrl-test.kartverket.no) 
 *
 * OpenAPI spec version: 0.6.59
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// KodeDTO
    /// </summary>
    [DataContract]
        public partial class KodeDTO :  IEquatable<KodeDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KodeDTO" /> class.
        /// </summary>
        /// <param name="navn">navn.</param>
        /// <param name="koder">koder.</param>
        public KodeDTO(string navn = default(string), List<string> koder = default(List<string>))
        {
            this.Navn = navn;
            this.Koder = koder;
        }
        
        /// <summary>
        /// Gets or Sets Navn
        /// </summary>
        [DataMember(Name="navn", EmitDefaultValue=false)]
        public string Navn { get; set; }

        /// <summary>
        /// Gets or Sets Koder
        /// </summary>
        [DataMember(Name="koder", EmitDefaultValue=false)]
        public List<string> Koder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KodeDTO {\n");
            sb.Append("  Navn: ").Append(Navn).Append("\n");
            sb.Append("  Koder: ").Append(Koder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KodeDTO);
        }

        /// <summary>
        /// Returns true if KodeDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of KodeDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KodeDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Navn == input.Navn ||
                    (this.Navn != null &&
                    this.Navn.Equals(input.Navn))
                ) && 
                (
                    this.Koder == input.Koder ||
                    this.Koder != null &&
                    input.Koder != null &&
                    this.Koder.SequenceEqual(input.Koder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Navn != null)
                    hashCode = hashCode * 59 + this.Navn.GetHashCode();
                if (this.Koder != null)
                    hashCode = hashCode * 59 + this.Koder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
