/* 
 * Nasjonalt Register over Luftfartshindre
 *
 * ## Autentisering Finn autoriserings token her: [https://nrl-test.kartverket.no/token/](https://nrl-test.kartverket.no/token/)   Trykk \"Authorize\" og skriv inn `Bearer <token>`  ## Kontakt oss Spørsmål kan sendes til [nrl@kartverket.no](mailto:nrl@kartverket.no) ## Annen dokumentasjon [Introduksjon til NRL](https://www.kartverket.no/geodataarbeid/nrl)   [SOSI-standardisert produktspesifikasjon - NRL rapportering](https://sosi.geonorge.no/produktspesifikasjoner/NRL-rapportering/)   [NRL - webklient](https://nrl-test.kartverket.no) 
 *
 * OpenAPI spec version: 0.6.59
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// KoderDTO
    /// </summary>
    [DataContract]
        public partial class KoderDTO :  IEquatable<KoderDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KoderDTO" /> class.
        /// </summary>
        /// <param name="alleKoder">alleKoder.</param>
        public KoderDTO(List<KodeDTO> alleKoder = default(List<KodeDTO>))
        {
            this.AlleKoder = alleKoder;
        }
        
        /// <summary>
        /// Gets or Sets AlleKoder
        /// </summary>
        [DataMember(Name="alleKoder", EmitDefaultValue=false)]
        public List<KodeDTO> AlleKoder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KoderDTO {\n");
            sb.Append("  AlleKoder: ").Append(AlleKoder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KoderDTO);
        }

        /// <summary>
        /// Returns true if KoderDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of KoderDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KoderDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AlleKoder == input.AlleKoder ||
                    this.AlleKoder != null &&
                    input.AlleKoder != null &&
                    this.AlleKoder.SequenceEqual(input.AlleKoder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AlleKoder != null)
                    hashCode = hashCode * 59 + this.AlleKoder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
