/* 
 * Nasjonalt Register over Luftfartshindre
 *
 * ## Autentisering Finn autoriserings token her: [https://nrl-test.kartverket.no/token/](https://nrl-test.kartverket.no/token/)   Trykk \"Authorize\" og skriv inn `Bearer <token>`  ## Kontakt oss Spørsmål kan sendes til [nrl@kartverket.no](mailto:nrl@kartverket.no) ## Annen dokumentasjon [Introduksjon til NRL](https://www.kartverket.no/geodataarbeid/nrl)   [SOSI-standardisert produktspesifikasjon - NRL rapportering](https://sosi.geonorge.no/produktspesifikasjoner/NRL-rapportering/)   [NRL - webklient](https://nrl-test.kartverket.no) 
 *
 * OpenAPI spec version: 0.6.59
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Kvalitet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KvalitetTests
    {
        // TODO uncomment below to declare an instance variable for Kvalitet
        //private Kvalitet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Kvalitet
            //instance = new Kvalitet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Kvalitet
        /// </summary>
        [Test]
        public void KvalitetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Kvalitet
            //Assert.IsInstanceOfType<Kvalitet> (instance, "variable 'instance' is a Kvalitet");
        }


        /// <summary>
        /// Test the property 'Datafangstmetode'
        /// </summary>
        [Test]
        public void DatafangstmetodeTest()
        {
            // TODO unit test for the property 'Datafangstmetode'
        }
        /// <summary>
        /// Test the property 'Nyaktighet'
        /// </summary>
        [Test]
        public void NyaktighetTest()
        {
            // TODO unit test for the property 'Nyaktighet'
        }
        /// <summary>
        /// Test the property 'DatafangstmetodeHyde'
        /// </summary>
        [Test]
        public void DatafangstmetodeHydeTest()
        {
            // TODO unit test for the property 'DatafangstmetodeHyde'
        }
        /// <summary>
        /// Test the property 'NyaktighetHyde'
        /// </summary>
        [Test]
        public void NyaktighetHydeTest()
        {
            // TODO unit test for the property 'NyaktighetHyde'
        }

    }

}
